## Proceso de limpieza dataset **energy_consumption**

In [60]:
import pandas as pd
import numpy as np

In [61]:
#Generar el data frame a partir del CSV en github
energy_consumption = pd.read_csv("https://github.com/Wolfgang93/emissionsCO2/blob/main/rawDataset/owid-energy-consumption-source.csv?raw=true")

In [62]:
energy_consumption.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,...,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,AFG,4832414.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,AFG,4879685.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,AFG,4935122.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,AFG,4998861.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,AFG,5063419.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
#Visualizar el data frame para elegir columnas
pd.options.display.max_columns = 50

##### ***Seleccion de campos***

In [64]:
#DataFrame para paises
countries = energy_consumption[['iso_code','country']]

In [65]:
#Lista para eliminar columnas
quitar_columnas = ['iso_code','biofuel_cons_change_pct','biofuel_cons_change_twh','biofuel_cons_per_capita','biofuel_consumption','biofuel_elec_per_capita','biofuel_electricity','biofuel_share_elec','biofuel_share_energy','coal_cons_change_pct','coal_cons_change_twh','coal_cons_per_capita','coal_prod_change_pct','coal_prod_change_twh','coal_prod_per_capita','coal_production','coal_share_elec','coal_share_energy','energy_cons_change_pct','energy_cons_change_twh','fossil_cons_change_pct','fossil_cons_change_twh','fossil_elec_per_capita','fossil_electricity','fossil_energy_per_capita','fossil_fuel_consumption','fossil_share_elec','fossil_share_energy','gas_cons_change_pct','gas_cons_change_twh','gas_prod_change_pct','gas_prod_change_twh','gas_prod_per_capita','gas_production','gas_share_elec','gas_share_energy','hydro_cons_change_pct','hydro_cons_change_twh','hydro_share_elec','hydro_share_energy','low_carbon_cons_change_pct','low_carbon_cons_change_twh','low_carbon_consumption','low_carbon_elec_per_capita','low_carbon_electricity','low_carbon_energy_per_capita','low_carbon_share_elec','low_carbon_share_energy','net_elec_imports','net_elec_imports_share_demand','nuclear_cons_change_pct','nuclear_cons_change_twh','nuclear_share_elec','nuclear_share_energy','oil_cons_change_pct','oil_cons_change_twh','oil_prod_change_pct','oil_prod_change_twh','oil_prod_per_capita','oil_production','oil_share_elec','oil_share_energy','other_renewable_exc_biofuel_electricity','other_renewables_cons_change_pct','other_renewables_cons_change_twh','other_renewables_elec_per_capita_exc_biofuel','other_renewables_share_elec','other_renewables_share_elec_exc_biofuel','other_renewables_share_energy','renewables_cons_change_pct', 'renewables_cons_change_twh','renewables_share_elec','renewables_share_energy','solar_cons_change_pct','solar_cons_change_twh','solar_share_elec','solar_share_energy','wind_cons_change_pct','wind_cons_change_twh','wind_share_elec','wind_share_energy','energy_per_gdp', 'gdp', 'primary_energy_consumption']

In [66]:
#Eliminar columnas
energy_consumption = energy_consumption.drop(quitar_columnas, axis=1)

In [67]:
energy_consumption.head()

,country,year,population,carbon_intensity_elec,coal_consumption,coal_elec_per_capita,coal_electricity,electricity_demand,electricity_generation,energy_per_capita,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,greenhouse_gas_emissions,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,other_renewable_consumption,other_renewable_electricity,other_renewables_elec_per_capita,other_renewables_energy_per_capita,per_capita_electricity,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita
0,Afghanistan,1900,4832414.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,4879685.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,4935122.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,4998861.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,5063419.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
energy_consumption.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22343 entries, 0 to 22342
Data columns (total 44 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   country                             22343 non-null  object
 1   year                                22343 non-null  int64
 2   population                          17971 non-null  float64
 3   carbon_intensity_elec               4834 non-null   float64
 4   coal_consumption                    6134 non-null   float64
 5   coal_elec_per_capita                5641 non-null   float64
 6   coal_electricity                    6437 non-null   float64
 7   electricity_demand                  5297 non-null   float64
 8   electricity_generation              7181 non-null   float64
 9   energy_per_capita                   10215 non-null  float64
 10  gas_consumption                     6094 non-null   float64
 11  gas_elec_per_capita                 5641 non-null   float64
 12  gas_electricity                     6438 non-null   float64
 13  gas_energy_per_capita               4866 non-null   float64
 14  greenhouse_gas_emissions            4947 non-null   float64
 15  hydro_consumption                   6153 non-null   float64
 16  hydro_elec_per_capita               7749 non-null   float64
 17  hydro_electricity                   9170 non-null   float64
 18  hydro_energy_per_capita             4862 non-null   float64
 19  nuclear_consumption                 5624 non-null   float64
 20  nuclear_elec_per_capita             7738 non-null   float64
 21  nuclear_electricity                 8808 non-null   float64
 22  nuclear_energy_per_capita           4684 non-null   float64
 23  oil_consumption                     6160 non-null   float64
 24  oil_elec_per_capita                 5641 non-null   float64
 25  oil_electricity                     6438 non-null   float64
 26  oil_energy_per_capita               4869 non-null   float64
 27  other_renewable_consumption         5948 non-null   float64
 28  other_renewable_electricity         8899 non-null   float64
 29  other_renewables_elec_per_capita    7615 non-null   float64
 30  other_renewables_energy_per_capita  4794 non-null   float64
 31  per_capita_electricity              6199 non-null   float64
 32  renewables_consumption              6153 non-null   float64
 33  renewables_elec_per_capita          7666 non-null   float64
 34  renewables_electricity              8939 non-null   float64
 35  renewables_energy_per_capita        4862 non-null   float64
 36  solar_consumption                   5924 non-null   float64
 37  solar_elec_per_capita               7666 non-null   float64
 38  solar_electricity                   8939 non-null   float64
 39  solar_energy_per_capita             4782 non-null   float64
 40  wind_consumption                    5939 non-null   float64
 41  wind_elec_per_capita                7663 non-null   float64
 42  wind_electricity                    8953 non-null   float64
 43  wind_energy_per_capita              4779 non-null   float64
dtypes: float64(42), int64(1), object(1)
memory usage: 7.5+ MB

##### ***Limpieza de datos***

In [69]:
# Eliminar duplicados en paises
countries.drop_duplicates(inplace=True)

In [70]:
#Eliminar duplicados en energy_consumption
energy_consumption.drop_duplicates(inplace=True)

In [71]:
#Llenar datos faltantes energy_consumption
energy_consumption = energy_consumption.fillna(0)

In [72]:
#Tomar años a partir de 1980
energy_consumption = energy_consumption[energy_consumption['year'] >= 1980]

In [73]:
#Eliminar comas
energy_consumption = energy_consumption.replace(',', ' ', regex=True)

In [74]:
#Cambiar tipo de valor
energy_consumption['population'] = energy_consumption['population'].astype(int)

##### ***Normalización de los valores del campo paises***

In [75]:
#Lista a considerar para los países 
countries_list = ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Czechoslovakia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macao', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Korea', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Western Sahara', 'Yemen',   'Yugoslavia', 'Zambia', 'Zimbabwe']

In [76]:
#Cambiar nombres de países
energy_consumption = energy_consumption.replace('Micronesia (country)','Micronesia')
energy_consumption = energy_consumption.replace('Central America (BP)','Central America')
energy_consumption = energy_consumption.replace('Guinea-Bissau','Guinea Bissau')
energy_consumption = energy_consumption.replace('Timor','Timor-Leste')

In [77]:
countries = countries.replace('Micronesia (country)','Micronesia')
countries = countries.replace('Central America (BP)','Central America')
countries = countries.replace('Guinea-Bissau','Guinea Bissau')
countries = countries.replace('Timor','Timor-Leste')

In [78]:
#Visualizar notación científica
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [79]:
#Generar DF con la lista de países
energy_consumption_by_country= energy_consumption[energy_consumption.country.isin(countries_list)]

In [80]:
countries = countries[countries.country.isin(countries_list)]

In [81]:
#Generar DF con las regiones que no se encuentran dentro de la lista
energy_consumption_groups = energy_consumption[~energy_consumption.country.isin(countries_list)]

In [82]:
#Verificar si ya no hay países por agregar a la lista
energy_consumption_groups['country'].unique()

array(['Africa', 'Africa (BP)', 'Africa (Shift)', 'Asia',
       'Asia & Oceania (EIA)', 'Asia Pacific (BP)',
       'Asia and Oceania (Shift)', 'Australia and New Zealand (EIA)',
       'CIS (BP)', 'Central & South America (EIA)', 'Central America',
       'Central and South America (Shift)', 'EU28 (Shift)',
       'East Germany (EIA)', 'Eastern Africa (BP)', 'Eurasia (EIA)',
       'Eurasia (Shift)', 'Europe', 'Europe (BP)', 'Europe (Shift)',
       'European Union (27)', 'European Union (EIA)', 'G20 (Ember)',
       'G7 (Ember)', 'Hawaiian Trade Zone (EIA)', 'High-income countries',
       'IEO - Africa (EIA)', 'IEO - Middle East (EIA)',
       'IEO OECD - Europe (EIA)', 'Latin America and Caribbean (Ember)',
       'Low-income countries', 'Lower-middle-income countries',
       'Mexico  Chile  and other OECD Americas (EIA)',
       'Middle Africa (BP)', 'Middle East (BP)', 'Middle East (EIA)',
       'Middle East (Ember)', 'Middle East (Shift)', 'Non-OECD (BP)',
       'Non-OECD (EIA)', 'Non-OPEC (EIA)', 'North America',
       'North America (BP)', 'North America (Shift)', 'OECD (BP)',
       'OECD (EIA)', 'OECD (Ember)', 'OECD (Shift)',
       'OECD - Asia And Oceania (EIA)', 'OECD - Europe (EIA)',
       'OECD - North America (EIA)', 'OPEC (EIA)', 'OPEC (Shift)',
       'OPEC - Africa (EIA)', 'OPEC - South America (EIA)', 'Oceania',
       'Other Africa (BP)', 'Other Asia Pacific (BP)', 'Other CIS (BP)',
       'Other Caribbean (BP)', 'Other Eastern Africa (BP)',
       'Other Europe (BP)', 'Other Middle Africa (BP)',
       'Other Middle East (BP)', 'Other Non-OECD - America (EIA)',
       'Other Non-OECD - Asia (EIA)',
       'Other Non-OECD - Europe and Eurasia (EIA)',
       'Other Northern Africa (BP)', 'Other South America (BP)',
       'Other South and Central America (BP)',
       'Other Southern Africa (BP)', 'Other Western Africa (BP)',
       'Persian Gulf (EIA)', 'Persian Gulf (Shift)',
       'Serbia and Montenegro', 'South America',
       'South Korea and other OECD Asia (EIA)',
       'South and Central America (BP)', 'Total Non-OPEC (BP)',
       'Total OPEC (BP)', 'U.S. Pacific Islands (EIA)',
       'U.S. Pacific Islands (Shift)', 'U.S. Territories (EIA)',
       'U.S. Territories (Shift)', 'USSR',
       'Upper-middle-income countries', 'Wake Island (EIA)',
       'Wake Island (Shift)', 'West Germany (EIA)', 'Western Africa (BP)',
       'World'], dtype=object)

In [83]:
#Generar DF con Continentes
energy_consumption_by_continent = energy_consumption[energy_consumption.country.isin(['Africa','Antartica','Asia','Central America','Europe','North America','Oceania','South America'])]

In [84]:
energy_consumption_by_continent

,country,year,population,carbon_intensity_elec,coal_consumption,coal_elec_per_capita,coal_electricity,electricity_demand,electricity_generation,energy_per_capita,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,greenhouse_gas_emissions,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,other_renewable_consumption,other_renewable_electricity,other_renewables_elec_per_capita,other_renewables_energy_per_capita,per_capita_electricity,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita
201,Africa,1980,476386229,0.000,543.557,0.000,0.000,0.000,0.000,3550.119,186.914,0.000,0.000,392.358,0.000,142.857,101.413,48.312,299.877,0.000,0.000,0.000,0.000,817.239,0.000,0.000,1715.496,0.661,0.207,0.435,1.387,0.000,143.518,101.848,48.519,301.264,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
202,Africa,1981,490003902,0.000,635.799,0.000,0.000,0.000,0.000,3871.944,228.491,0.000,0.000,466.305,0.000,148.420,102.434,50.193,302.895,0.000,0.000,0.000,0.000,883.862,0.000,0.000,1803.785,0.696,0.218,0.445,1.420,0.000,149.116,102.879,50.411,304.315,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
203,Africa,1982,504034174,0.000,701.176,0.000,0.000,0.000,0.000,4012.326,246.734,0.000,0.000,489.517,0.000,148.459,99.609,50.206,294.542,0.000,0.000,0.000,0.000,925.227,0.000,0.000,1835.644,0.753,0.236,0.468,1.495,0.000,149.213,100.077,50.442,296.037,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
204,Africa,1983,518479760,0.000,713.246,0.000,0.000,0.000,0.000,4018.678,271.275,0.000,0.000,523.213,0.000,133.795,87.269,45.247,258.053,0.000,0.000,0.000,0.000,964.552,0.000,0.000,1860.347,0.734,0.230,0.444,1.416,0.000,134.530,87.713,45.477,259.469,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
205,Africa,1984,533345153,0.000,762.898,0.000,0.000,0.000,0.000,4027.398,259.903,0.000,0.000,487.307,0.000,131.556,83.417,44.490,246.663,11.137,7.359,3.925,20.882,981.752,0.000,0.000,1840.744,0.747,0.234,0.439,1.401,0.000,132.303,83.856,44.724,248.063,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18296,South America,2017,419903920,191.557,358.694,145.935,61.279,1136.680,1167.536,16866.697,1538.714,554.411,232.799,3664.442,223.650,1786.480,1598.659,671.283,4254.496,55.741,51.981,21.827,132.748,2738.072,131.078,55.040,6520.711,215.566,67.542,160.850,513.370,2780.484,2154.165,1895.636,795.985,5130.138,14.538,13.010,5.463,34.622,137.581,123.117,51.697,327.649
18297,South America,2018,423581091,182.854,350.587,141.059,59.750,1154.070,1176.839,16526.049,1470.750,529.720,224.379,3472.180,215.190,1801.076,1607.128,680.749,4252.022,57.240,53.227,22.546,135.134,2638.777,113.240,47.966,6229.685,226.570,71.020,167.665,534.891,2778.309,2213.234,1940.396,821.915,5225.054,26.857,23.965,10.151,63.404,158.731,141.638,59.995,374.736
18298,South America,2019,427199423,179.482,345.465,142.457,60.857,1173.420,1180.344,16209.313,1398.971,527.993,225.558,3274.750,211.850,1763.960,1566.453,669.188,4129.126,62.154,57.518,24.572,145.491,2595.695,91.725,39.185,6076.073,231.006,72.407,169.493,540.745,2762.982,2227.373,1942.331,829.763,5213.895,41.052,36.456,15.574,96.096,191.354,169.929,72.593,447.928
18299,South America,2020,430759772,177.438,306.102,132.701,57.162,1170.470,1161.252,15031.484,1270.646,481.075,207.228,2949.778,206.050,1740.007,1538.061,662.535,4039.392,62.286,57.375,24.715,144.596,2318.180,72.318,31.152,5381.608,244.669,76.698,178.052,567.993,2695.823,2250.391,1950.989,840.407,5224.237,56.676,50.098,21.580,131.572,209.039,184.778,79.595,485.280
18300,South America,2021,434260136,166.185,340.193,133.166,57.829,1007.280,1215.575,15835.877,1414.688,576.755,250.462,3257.697,202.010,1643.830,1446.628,628.213,3785.357,64.120,58.804,25.536,147.654,2549.028,107.444,46.659,5869.818,231.720,72.659,167.317,533.598,2799.185,2225.141,1921.596,834.473,5123.981,83.139,73.165,31.773,191.449,266.452,234.487,101.828,613.576

#### Normalización de tabla ***energy_consumption_by_country***

**Creamos columna ficticia**: coal_energy_per_capita

In [85]:
energy_consumption_by_country['coal_energy_per_capita'] = np.zeros(len(energy_consumption_by_country))

C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\707018292.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy_consumption_by_country['coal_energy_per_capita'] = np.zeros(len(energy_consumption_by_country))

In [86]:
energy_consumption_by_country.head()

,country,year,population,carbon_intensity_elec,coal_consumption,coal_elec_per_capita,coal_electricity,electricity_demand,electricity_generation,energy_per_capita,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,greenhouse_gas_emissions,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,other_renewable_consumption,other_renewable_electricity,other_renewables_elec_per_capita,other_renewables_energy_per_capita,per_capita_electricity,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,coal_energy_per_capita
80,Afghanistan,1980,13356500,0.000,0.000,0.000,0.000,0.000,0.000,583.294,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
81,Afghanistan,1981,13171679,0.000,0.000,0.000,0.000,0.000,0.000,666.378,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
82,Afghanistan,1982,12882518,0.000,0.000,0.000,0.000,0.000,0.000,725.660,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
83,Afghanistan,1983,12537732,0.000,0.000,0.000,0.000,0.000,0.000,912.140,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
84,Afghanistan,1984,12204306,0.000,0.000,0.000,0.000,0.000,0.000,941.393,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

##### ***Tabla population_country_electricity***

In [87]:
population_country_electricity = energy_consumption_by_country[['country','year', 'electricity_demand', 'electricity_generation', 'population']]

In [88]:
population_country_electricity.head()

        country  year  electricity_demand  electricity_generation  population
80  Afghanistan  1980               0.000                   0.000    13356500
81  Afghanistan  1981               0.000                   0.000    13171679
82  Afghanistan  1982               0.000                   0.000    12882518
83  Afghanistan  1983               0.000                   0.000    12537732
84  Afghanistan  1984               0.000                   0.000    12204306

In [89]:
population_country_electricity.columns = ['country','year', 'electricityDemand', 'electricityGeneration', 'population']

In [90]:
population_country_electricity.head()

        country  year  electricityDemand  electricityGeneration  population
80  Afghanistan  1980              0.000                  0.000    13356500
81  Afghanistan  1981              0.000                  0.000    13171679
82  Afghanistan  1982              0.000                  0.000    12882518
83  Afghanistan  1983              0.000                  0.000    12537732
84  Afghanistan  1984              0.000                  0.000    12204306

In [91]:
population_country_electricity.drop_duplicates(subset = ['country', 'year'],  inplace=True)

C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1162506636.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_country_electricity.drop_duplicates(subset = ['country', 'year'],  inplace=True)

In [92]:
population_country_electricity.reset_index(drop=True).to_csv('../normalizedDataset_2/population_country_electricity_consumption.csv', header=True, index=False)

##### ***Tabla source_country_electricity*** , parte consumption y production

**Pivoteo de columnas**

In [93]:
# Normalizacion en nombres de columnas
energy_consumption_by_country = energy_consumption_by_country.rename(columns={'other_renewable_consumption':'other_renewables_consumption','other_renewable_electricity':'other_renewables_electricity'})

In [94]:
energy_consumption_by_country.head()

,country,year,population,carbon_intensity_elec,coal_consumption,coal_elec_per_capita,coal_electricity,electricity_demand,electricity_generation,energy_per_capita,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,greenhouse_gas_emissions,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,other_renewables_consumption,other_renewables_electricity,other_renewables_elec_per_capita,other_renewables_energy_per_capita,per_capita_electricity,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,coal_energy_per_capita
80,Afghanistan,1980,13356500,0.000,0.000,0.000,0.000,0.000,0.000,583.294,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
81,Afghanistan,1981,13171679,0.000,0.000,0.000,0.000,0.000,0.000,666.378,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
82,Afghanistan,1982,12882518,0.000,0.000,0.000,0.000,0.000,0.000,725.660,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
83,Afghanistan,1983,12537732,0.000,0.000,0.000,0.000,0.000,0.000,912.140,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
84,Afghanistan,1984,12204306,0.000,0.000,0.000,0.000,0.000,0.000,941.393,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [95]:
# Eliminacion de columnas no involucradas
population_source_electricity = energy_consumption_by_country.drop(['population','carbon_intensity_elec','electricity_demand','electricity_generation','energy_per_capita','greenhouse_gas_emissions'], axis=1)

In [96]:
population_source_electricity.head()

,country,year,coal_consumption,coal_elec_per_capita,coal_electricity,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,other_renewables_consumption,other_renewables_electricity,other_renewables_elec_per_capita,other_renewables_energy_per_capita,per_capita_electricity,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,coal_energy_per_capita
80,Afghanistan,1980,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
81,Afghanistan,1981,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
82,Afghanistan,1982,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
83,Afghanistan,1983,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
84,Afghanistan,1984,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [97]:
# Cantidad de fuentes de produccion electrica
n_sources = len(energy_consumption_by_country.columns[energy_consumption_by_country.columns.str.match(r'(.*_elec_per_capita$)')])
n_sources

9

Tipos de fuentes de energia encontradas

In [98]:
sources = ['coal', 'gas', 'hydro', 'nuclear', 'oil', 'other_renewables', 'renewables', 'solar', 'wind']

Columnas de sufijos repetidos: '_consumption', '_elec_per_capita', '_electricity', '_energy_per_capita'

In [99]:
cols = ['country','year', 'source', 'consumptionElectricity', 'productionElectricity', 'energyPerCapita', 'elecPerCapita']

Uniendo todo en un DataFrame central, sin repetición de columnas

In [100]:
base_df = pd.DataFrame(columns = ['country','year', 'source', 'consumptionElectricity', 'productionElectricity', 'energyPerCapita', 'elecPerCapita'])

In [101]:
for n in sources:
    agg = population_source_electricity[['country', 'year', f"{n}_consumption", f"{n}_electricity", f"{n}_energy_per_capita", f"{n}_elec_per_capita"]]
    agg.columns = ['country','year','consumptionElectricity', 'productionElectricity', 'energyPerCapita', 'elecPerCapita']
    agg.insert(2, 'source', n)
    base_df = base_df.append(agg)

C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)
C:\Users\Ale\AppData\Local\Temp\ipykernel_7588\1549010059.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  base_df = base_df.append(agg)

In [102]:
base_df.head()

,country,year,source,consumptionElectricity,productionElectricity,energyPerCapita,elecPerCapita
80,Afghanistan,1980,coal,0.000,0.000,0.000,0.000
81,Afghanistan,1981,coal,0.000,0.000,0.000,0.000
82,Afghanistan,1982,coal,0.000,0.000,0.000,0.000
83,Afghanistan,1983,coal,0.000,0.000,0.000,0.000
84,Afghanistan,1984,coal,0.000,0.000,0.000,0.000

In [103]:
base_df.drop_duplicates(subset=['country', 'year', 'source'], inplace=True)
base_df.sort_values(by=['country','year','source'], inplace=True)

In [104]:
base_df

,country,year,source,consumptionElectricity,productionElectricity,energyPerCapita,elecPerCapita
80,Afghanistan,1980,coal,0.000,0.000,0.000,0.000
80,Afghanistan,1980,gas,0.000,0.000,0.000,0.000
80,Afghanistan,1980,hydro,0.000,0.000,0.000,0.000
80,Afghanistan,1980,nuclear,0.000,0.000,0.000,0.000
80,Afghanistan,1980,oil,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...
22342,Zimbabwe,2021,oil,0.000,0.000,0.000,0.000
22342,Zimbabwe,2021,other_renewables,0.000,0.000,0.000,0.000
22342,Zimbabwe,2021,renewables,0.000,0.000,0.000,0.000
22342,Zimbabwe,2021,solar,0.000,0.000,0.000,0.000
22342,Zimbabwe,2021,wind,0.000,0.000,0.000,0.000

In [105]:
base_df.reset_index(drop=True).to_csv('../normalizedDataset_2/source_country_electricity_consumption.csv', header=True, index=False)

##### ***Tabla country***

In [106]:
len(countries)

222

In [107]:
country = countries.fillna(0).reset_index(drop=True).reset_index().rename(columns={'index':'idCountry'})

In [108]:
country

     idCountry iso_code         country
0            0      AFG     Afghanistan
1            1      ALB         Albania
2            2      DZA         Algeria
3            3      ASM  American Samoa
4            4      AGO          Angola
..         ...      ...             ...
217        217      ESH  Western Sahara
218        218      YEM           Yemen
219        219        0      Yugoslavia
220        220      ZMB          Zambia
221        221      ZWE        Zimbabwe

[222 rows x 3 columns]

In [109]:
country.loc[country.country=='Yugoslavia', 'iso_code']= 'YUG'
country.loc[country.country=='Czechoslovakia', 'iso_code']='CSK'

In [110]:
country.sort_values(by='country').to_csv('../Modelo_ER/country.csv', index=False)

##### ***Subiendo al github***

In [111]:
#Generar token para acceso al repo de git
#from github import Github
#token = ''
#g = Github(token)

ImportError: cannot import name 'Github' from 'github' (c:\Users\Ale\AppData\Local\Programs\Python\Python310\lib\site-packages\github\__init__.py)

In [ ]:
#Accesar a repo de git
#repo = g.get_repo('')

In [ ]:
#Crear/Actualizar csv por continente en el repo de git
#try:
#    repo.create_file('energy-consumption-source_by_continent.csv','Limpieza consumo de energía por continente', energy_consumption_by_continent.to_csv(index = False))
#except:
#    contents = repo.get_contents('energy-consumption-source_by_continent.csv')
#    repo.update_file(contents.path, 'Actualización, limpieza consumo de energía por continente', energy_consumption_by_continent.to_csv(index = False), contents.sha)

In [ ]:
#Crear/Actualizar csv por país en el repo de git
#try:
#    repo.create_file('energy-consumption-source_by_country.csv','Limpieza consumo de energía por país', energy_consumption_by_country.to_csv(index = False))
#except:
#    contents = repo.get_contents('energy-consumption-source_by_country.csv')
#    repo.update_file(contents.path, 'Actualización, limpieza consumo de energía por país', energy_consumption_by_country.to_csv(index = False), contents.sha)

In [112]:
energy_consumption_by_continent.to_csv('../normalizedDataset/energy-consumption-source_by_continent.csv',index = False)

In [113]:
energy_consumption_by_country.to_csv('../normalizedDataset/energy-consumption-source_by_country.csv',index = False)

In [114]:
#Generar DF mundial
energy_consumption_world = energy_consumption[energy_consumption['country'] == 'World']

In [115]:
#Crear/Actualizar csv mundial en el repo git
#try:
#    repo.create_file('energy-consumption-source_world.csv','Limpieza consumo de energía mundial', energy_consumption_world.to_csv(index = False))
#except:
#    contents = repo.get_contents('energy-consumption-source_world.csv')
#    repo.update_file(contents.path, 'Actualización, limpieza consumo de energía mundial', energy_consumption_world.to_csv(index = False), contents.sha)

In [116]:
energy_consumption_world.to_csv('../normalizedDataset/energy-consumption-source_world.csv',index = False)

In [117]:
#Generar DF Grupo G20
energy_consumption_G20 = energy_consumption[energy_consumption['country'] == 'G20 (Ember)']

In [118]:
#Crear/Actualizar csv G20 en el repo git
#try:
#    repo.create_file('energy-consumption-source_G20.csv','Limpieza consumo de energía G20', energy_consumption_G20.to_csv(index = False))
#except:
#    contents = repo.get_contents('energy-consumption-source_G20.csv')
#    repo.update_file(contents.path, 'Actualización, limpieza consumo de energía G20', energy_consumption_G20.to_csv(index = False), contents.sha)

In [119]:
energy_consumption_G20.to_csv('../normalizedDataset/energy-consumption-source_G20.csv',index = False)